config:
  azure-native:location: centralindia
  fastapi-react-starter:environment: production
  fastapi-react-starter:location: eastasia
  fastapi-react-starter:dbName: appdb
  fastapi-react-starter:dbUser: pgadmin
  fastapi-react-starter:dbPassword:
    secure: AAABAPnt5xQcmgpwv4jpBAlAOZShe+KBILsZCTfyw0Oh7y4z4z0Ls8s1CgAt9sgS2Qs=
  fastapi-react-starter:jwtKey:
    secure: AAABAAF2kHNiJXsvkd9r8LzjkODiUMdZf4pnKlclfbyF4iXYYA==
  fastapi-react-starter:backendImage: docker.io/surajchauhan24/fastapi-backend:latest
  fastapi-react-starter:backendImageAcr: myappproduction.azurecr.io/fastapi-backend:latest
  fastapi-react-starter:dbPort: "5432"
  fastapi-react-starter:websitePort: "8000"
