# name: CI-CD

# on:
#   push:
#     branches:
#       - main

# jobs:

#   ci:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"

#       - name: Install backend dependencies
#         run: |
#           cd fastapi-react-starter/backend
#           pip install -r requirements.txt

#       - name: Run tests
#         run: |
#           cd fastapi-react-starter/backend
#           pytest


#   build:
#     needs: ci
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Login to DockerHub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

#       - name: Build backend image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:latest fastapi-react-starter/backend

#       - name: Build frontend image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest fastapi-react-starter/frontend

#       - name: Push images
#         run: |
#           docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:latest
#           docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest


#   frontend-build:
#     needs: ci
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"

#       - name: Install frontend dependencies
#         run: |
#           cd fastapi-react-starter/frontend
#           npm install

#       - name: Build React app
#         run: |
#           cd fastapi-react-starter/frontend
#           echo "VITE_API_URL=https://myapp-dev-test-api-apif337205f.azurewebsites.net" > .env.production
#           npm run build


#   frontend-deploy:
#     needs: frontend-build
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Deploy to Azure Static Web Apps
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           action: "upload"
#           app_location: "fastapi-react-starter/frontend"
#           output_location: "dist"


#   deploy:
#     needs: [build, frontend-build]
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"

#       - name: Install Pulumi CLI
#         uses: pulumi/actions@v5

#       - name: Install Infra dependencies
#         run: |
#           cd infra
#           pip install -r requirements.txt

#       - name: Pulumi Login
#         run: pulumi login
#         env:
#           PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

#       - name: Azure Login
#         uses: azure/login@v2
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Select stack
#         run: pulumi stack select dev-test || pulumi stack init dev-test
#         working-directory: infra

#       - name: Pulumi Preview
#         run: pulumi preview
#         working-directory: infra

#       - name: Deploy infrastructure
#         run: pulumi up --yes --non-interactive --parallel 1
#         working-directory: infra




# # ----------------------------------------------------------------------------------------------
# # # This is approch using Docker Image
# # ---------------------------------------------------------------------------------------------
#   name: CI-CD

#   on:
#     push:
#       branches:
#         - main

#   env:
#     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

#   jobs:

#   # =========================================================
#   # 1️⃣ CI - Run backend tests
#   # =========================================================
#     ci:
#       runs-on: ubuntu-latest

#       steps:
#         - uses: actions/checkout@v4

#         - name: Setup Python
#           uses: actions/setup-python@v5
#           with:
#             python-version: "3.12"

#         - name: Install backend dependencies
#           run: |
#             cd fastapi-react-starter/backend
#             pip install -r requirements.txt

#         - name: Run tests
#           run: |
#             cd fastapi-react-starter/backend
#             pytest


#   # =========================================================
#   # 2️⃣ Build & Push Docker Images
#   # =========================================================
#     build:
#       needs: ci
#       runs-on: ubuntu-latest

#       steps:
#         - uses: actions/checkout@v4

#         - name: Login DockerHub
#           run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

#         - name: Build backend image
#           run: |
#             docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:${{ github.sha }} fastapi-react-starter/backend

#         - name: Build frontend image
#           run: |
#             docker build -t ${{ secrets.DOCKER_USERNAME }}/react-frontend:${{ github.sha }} fastapi-react-starter/frontend

#         - name: Push images
#           run: |
#             docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:${{ github.sha }}
#             docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend:${{ github.sha }}


#   # =========================================================
#   # 3️⃣ Deploy Infrastructure via Pulumi
#   # =========================================================
#     deploy-infra:
#       needs: build
#       runs-on: ubuntu-latest

#       steps:
#         - uses: actions/checkout@v4

#         - name: Setup Python
#           uses: actions/setup-python@v5
#           with:
#             python-version: "3.12"

#         - name: Install Pulumi CLI
#           uses: pulumi/actions@v5

#         - name: Install Infra dependencies
#           run: |
#             cd infra
#             pip install -r requirements.txt

#         - name: Pulumi Login
#           run: pulumi login

#         - name: Azure Login
#           uses: azure/login@v2
#           with:
#             creds: ${{ secrets.AZURE_CREDENTIALS }}

#         - name: Select stack
#           run: pulumi stack select surajchouhan24-org/dev-test
#           working-directory: infra

#         - name: Preview Infrastructure
#           run: pulumi preview
#           working-directory: infra

#         - name: Deploy Infrastructure
#           run: pulumi up --yes --non-interactive
#           working-directory: infra


#   # =========================================================
#   # 4️⃣ Build React with Dynamic API URL
#   # =========================================================
#     frontend-build:
#       needs: deploy-infra
#       runs-on: ubuntu-latest

#       steps:
#         - uses: actions/checkout@v4

#         - name: Setup Node
#           uses: actions/setup-node@v4
#           with:
#             node-version: "20"

#         - name: Install Pulumi CLI
#           uses: pulumi/actions@v5

#         - name: Pulumi Login
#           run: pulumi login

#         - name: Select stack
#           run: pulumi stack select surajchouhan24-org/dev-test
#           working-directory: infra

#         - name: Get API URL from Pulumi
#           id: api
#           run: |
#             API_URL=$(cd infra && pulumi stack output apiUrl)
#             echo "api_url=$API_URL" >> $GITHUB_OUTPUT

#         - name: Install frontend dependencies
#           run: |
#             cd fastapi-react-starter/frontend
#             npm install

#         - name: Create env file
#           run: |
#             cd fastapi-react-starter/frontend
#             echo "VITE_API_URL=${{ steps.api.outputs.api_url }}" > .env.production
#             cat .env.production

#         - name: Build React
#           run: |
#             cd fastapi-react-starter/frontend
#             npm run build

#         - name: Upload build artifact
#           uses: actions/upload-artifact@v4
#           with:
#             name: react-build
#             path: fastapi-react-starter/frontend/dist


#   # =========================================================
#   # 5️⃣ Deploy React to Azure Static Web Apps
#   # =========================================================
#     frontend-deploy:
#       needs: frontend-build
#       runs-on: ubuntu-latest

#       steps:
#         - uses: actions/checkout@v4

#         - name: Install Pulumi CLI
#           uses: pulumi/actions@v5

#         - name: Pulumi Login
#           run: pulumi login

#         - name: Select stack
#           run: pulumi stack select surajchouhan24-org/dev-test
#           working-directory: infra

#         - name: Download React build
#           uses: actions/download-artifact@v4
#           with:
#             name: react-build
#             path: fastapi-react-starter/frontend/dist

#         - name: Get Static Web App token
#           id: swa
#           run: |
#             TOKEN=$(cd infra && pulumi stack output staticWebAppToken)
#             echo "token=$TOKEN" >> $GITHUB_OUTPUT

#         - name: Deploy to Azure Static Web Apps
#           uses: Azure/static-web-apps-deploy@v1
#           with:
#             azure_static_web_apps_api_token: ${{ steps.swa.outputs.token }}
#             repo_token: ${{ secrets.GITHUB_TOKEN }}
#             action: upload
#             app_location: "fastapi-react-starter/frontend/dist"
#             skip_app_build: true


name: CI-CD

on:
  push:
    branches:
      - main

concurrency:
  group: dev-deploy
  cancel-in-progress: true

env:
  IMAGE_NAME: fastapi-backend
  IMAGE_TAG: ${{ github.sha }}

jobs:

# ---------------- Backend Tests ----------------

  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fastapi-react-starter/backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - run: pip install -r requirements.txt
      - run: pytest

  # ---------------- Deploy Base Infrastructure ----------------

  deploy-infra-base:
    needs: test-backend
    runs-on: ubuntu-latest

    defaults:   
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: pulumi/setup-pulumi@v2

      - name: Pulumi Login
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - run: pulumi stack select surajchouhan24-org/dev-test --non-interactive

      - run: pip install -r requirements.txt

      - run: pulumi up --yes --non-interactive


  # ---------------- Build & Push Docker Image ----------------

  build-backend:
    needs: deploy-infra-base
    runs-on: ubuntu-latest

    outputs:
      login_server: ${{ steps.acr.outputs.login_server }}

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: pulumi/setup-pulumi@v2

      - name: Pulumi Login
        run: pulumi login
        working-directory: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Select Stack
        run: pulumi stack select surajchouhan24-org/dev-test --non-interactive
        working-directory: infra

      - name: Get ACR login server
        id: acr
        run: |
          LOGIN_SERVER=$(pulumi stack output acrLoginServer)
          echo "login_server=$LOGIN_SERVER" >> $GITHUB_OUTPUT
        working-directory: infra

      - name: Login to ACR
        run: |
          az acr login --name $(echo ${{ steps.acr.outputs.login_server }} | cut -d'.' -f1)

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ steps.acr.outputs.login_server }}/${IMAGE_NAME}:${IMAGE_TAG} \
          fastapi-react-starter/backend

      - name: Push Docker Image
        run: |
          docker push \
          ${{ steps.acr.outputs.login_server }}/${IMAGE_NAME}:${IMAGE_TAG}


  # ---------------- Deploy Backend ----------------

  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: pulumi/setup-pulumi@v2

      - name: Pulumi Login
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - run: pulumi stack select surajchouhan24-org/dev-test --non-interactive

      - name: Set backend image
        run: |
          pulumi config set backendImageAcr \
          ${{ needs.build-backend.outputs.login_server }}/${IMAGE_NAME}:${IMAGE_TAG}

      - run: pulumi up --yes --non-interactive

  # ---------------- Build Frontend ----------------

  build-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fastapi-react-starter/frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm install

      - name: Get API URL
        id: api
        run: |
          cd ../../infra
          pulumi login
          pulumi stack select surajchouhan24-org/dev-test
          API_URL=$(pulumi stack output apiUrl)
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Create env file
        run: |
          echo "VITE_API_URL=${{ steps.api.outputs.api_url }}" > .env.production

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist

  # ---------------- Deploy Frontend ----------------

  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pulumi/setup-pulumi@v2

      - name: Get Static Web App Token
        id: swa
        run: |
          cd infra
          pulumi login
          pulumi stack select surajchouhan24-org/dev-test
          TOKEN=$(pulumi stack output staticWebAppToken)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: react-build
          path: fastapi-react-starter/frontend/dist

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.swa.outputs.token }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "fastapi-react-starter/frontend/dist"
          skip_app_build: true
