name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fastapi-react-starter/backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black

      - name: Check formatting with black
        run: black --check app/


  frontend-format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fastapi-react-starter/frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check formatting with prettier
        run: npm run format:check